= Red Hat Developers Workshop Guide

How to setup the workshop using OpenShift4 
  
== OCP4 Setup

Create a OCP4 cluster by visiting try.openshift.com

1) ./openshift-install --dir=june22v2 create install-config

This creates a directory called "june22v2" and inside it a file called install-config.yaml

2) Edit this file to override your AWS Instance Types, here is an example snippet

----
  name: worker
  platform: 
     aws:
       type: m5.4xlarge

  name: master
  platform: 
     aws:
       type: c5.4xlarge
----

3) ./openshift-install --dir=june22v2 create cluster

4) You can monitoring the activity by refreshing your AWS EC2 console

5) Make note of the resulting URLs and the kubeadmin password when the process is completed.  It will take several minutes, go have lunch.

6) Also keep the kubeconfig file in june22v2/auth

7) OpenShift4 CLI for your environment from https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/.

[IMPORTANT]
====
If you not have OCP4 cluster then please proceed to https://try.openshift.com[try.openshift.com] to get one installed and configured before proceeding to next section.
====

== Setup Workshop

```
node setup.js -k /Users/home/foo/kubeconfig -a 'fooPassword'
```
