runtime:
  cache_dir: ./.cache/antora

site:
  title: Summit Guru Night
  url: https://summit-guru-night.devx.red
  start_page: summit-guru-night::index.adoc

content:
  sources:
    - url: https://github.com/redhat-developer-demos/guru-night
      branches: master
      start_path: documentation
    - url: https://github.com/redhat-developer-demos/knative-tutorial
      branches: workshop/0.4
      start_path: documentation
    - url: https://github.com/redhat-developer-demos/istio-tutorial
      branches: workshop/1.1.x
      start_path: documentation
    - url: https://github.com/redhat-developer-demos/eda-tutorial
      branches: master
      start_path: documentation
asciidoc:
  attributes:
    title: Summit Guru Night
    istio-tutorial-namespace: $WORKSHOP_USER-istiotutorial
    tutorial-namespace: $WORKSHOP_USER-knativetutorial
    workshop: true
    ocpurl: https://api.guru.devx.red:6443
    appdomain: apps.guru.devx.red
    etherpad: https://etherpad.wikimedia.org/p/SummitGuruNight
    namespace-suffix: -$WORKSHOP_USER
    workshop-domain: guru.devx.red
    workshop-version: release/0.4
  extensions:
    - ./lib/copy-to-clipboard.js
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui
output:
  dir: ./gh-pages
