runtime:
  cache_dir: ./.cache/antora

site:
  title: Summit Guru Night
  url: https://summit-guru-night.dex.red
  start_page: summit-guru-night::index.adoc

content:
  sources:
    - url: .
      branches: HEAD
      start_path: documentation
    - url: /knative-tutorial
      #branches: workshop/*
      start_path: documentation
    - url: /istio-tutorial
      #branches: workshop/*
      start_path: documentation
asciidoc:
  attributes:
    istio-tutorial-namespace: $WORKSHOP_USER-istiotutorial
    knative-tutorial-namespace: $WORKSHOP_USER-knativetutorial
    workshop: true
    ocpurl: https://api.guru.devx.red:6443
    appdomain: apps.guru.devx.red
    etherpad: https://etherpad.wikimedia.org/p/IstioIstambul
    namespace-suffix: -$WORKSHOP_USER
    workshop-domain: guru.devx.red
    workshop-version: release/0.4
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
  supplemental_files: ./supplemental-ui
output:
  dir: ./gh-pages
