#!/bin/bash

annotateProjects::run(){
  
  local projects=$(readopt -n --projects)
  if [ -z $projects ]; then 
     projects=($PROJECTS)
  fi
  
  local user_from=$(readopt -f --from)
  if [ -z $user_from ]; then 
     user_from=$USERS_FROM
  fi

  local user_to=$(readopt -t --to)
  if [ -z $user_to ]; then 
     user_to=$USERS_TO
  fi
  
  local user_prefix=$(readopt -p --prefix)
   if [ -z $user_prefix ]; then 
     user_prefix=$USER_PREFIX
  fi

  for ((i=$user_from; i<=user_to ; i++ ));
  do
    for p in "${projects[@]}" 
    do
      openshiftUser=$(printf "$user_prefix%d" $i)
      openshiftProject=$(printf '%s-%d' $p $i)
      printf "Annotating OpenShift Project $openshiftProject with user $openshiftUser \n"
      oc annotate ns "$openshiftProject" --overwrite "openshift.io/requester=$openshiftUser"
    done
  done
}

annotateProjects::usage(){
   cat <<EOT
  -f --from <user count from>    The starting user count e.g. 1
  -t --to <user count to>        The ending user count e.g. 10
  -p --prefix <userprefix>       The username prefix e.g. user
  -n --projects <userpojects>    The space user project name prefixes e.g. tutorial
EOT
}

annotateProjects::description(){
  echo "Annotates the project(s) with right workshop user"
}
