#!/bin/bash

createWorkspaces::run(){
  # Check if pre-req commands exists
  hash chectl
  hash jq
  hash http

  NL=$'\n'

  local user_from=$(readopt -f --from)
  if [ -z $user_from ]; then 
     user_from=$USERS_FROM
  fi

  local user_to=$(readopt -t --to)
  if [ -z $user_to ]; then 
     user_to=$USERS_TO
  fi
  
  local user_prefix=$(readopt -p --prefix)
   if [ -z $user_prefix ]; then 
     user_prefix=$USER_PREFIX
  fi
  
  for ((i=$user_from; i<=user_to ; i++ ));
  do
    CHE_USER="$user_prefix$i"
    CHE_PASSWORD="${WORKSHOP_USER_DEFAULT_PASSWORD}"
    oc login -u $CHE_USER -p $CHE_PASSWORD $OPENSHIFT_API_URL &>/dev/null
    SUBJECT_TOKEN=$(oc whoami --show-token)
    # echo "$SUBJECT_TOKEN"
    TOKEN_ENDPOINT="http://${CHE_KEYCLOAK_URL}/auth/realms/che/protocol/openid-connect/token"
    CHE_ACCESS_TOKEN=$(http --form $TOKEN_ENDPOINT client_id='che-public' \
     grant_type='urn:ietf:params:oauth:grant-type:token-exchange' \
     subject_token="${SUBJECT_TOKEN}" \
     subject_issuer='openshift-v4' \
     subject_token_type='urn:ietf:params:oauth:token-type:access_token'| jq -r .access_token)
    echo "User: $CHE_USER $NL Token: $CHE_ACCESS_TOKEN"
    oc logout &>/dev/null
  done
}

createWorkspaces::usage(){
   cat <<EOT
  -f --from <user count from>    The starting user count e.g. 1
  -t --to <user count to>        The ending user count e.g. 10
  -p --prefix <userprefix>       The username prefix e.g. user
EOT
}

createWorkspaces::description(){
  echo "Creates Che workspace for each workshop user"
}
