#!/bin/bash
createWorkspaces::run(){

  local cheKeyCloakUrl="https://$(oc get routes -n che keycloak -o yaml | yq r - 'spec.host')"
  local tokenEndpoint="$cheKeyCloakUrl/auth/realms/che/protocol/openid-connect/token"

  # Check if pre-req commands exists
  hash chectl
  hash jq
  hash http

  NL=$'\n'

  local user_from=$(readopt -f --from)
  if [ -z $user_from ]; then 
     user_from=$USERS_FROM
  fi

  local user_to=$(readopt -t --to)
  if [ -z $user_to ]; then 
     user_to=$USERS_TO
  fi
  
  local user_prefix=$(readopt -p --prefix)
   if [ -z $user_prefix ]; then 
     user_prefix=$USER_PREFIX
  fi
  
  local key_cloak_admin_password=$(oc get -n che deployment keycloak -o jsonpath='{.spec.template.spec.containers[*].env[?(@.name=="KEYCLOAK_PASSWORD")].value}')
  local che_keycloak_url="https://$(oc get routes -n che keycloak -o yaml | yq r - 'spec.host')"
  
  local master_realm_endpoint="$che_keycloak_url/auth/realms/master/protocol/openid-connect/token"
  local che_realm_endpoint="$che_keycloak_url/auth/realms/che/protocol/openid-connect/token"


  for ((i=$user_from; i<=user_to ; i++ ));
  do
    local che_user="$user_prefix$i"
    local che_user_password="${WORKSHOP_USER_DEFAULT_PASSWORD}" 
    
    local subject_token=$(oc logout &> /dev/null && \
      oc login -u "$che_user" -p "$che_user_password" "$OPENSHIFT_API_URL" &> /dev/null &&\
      oc whoami --show-token)
      
    #echo "Subject Token: $subject_token"
        
    local access_token=$(http --form POST $che_realm_endpoint \
    grant_type='urn:ietf:params:oauth:grant-type:token-exchange' \
    client_id="che-public" \
    subject_token="$subject_token" subject_issuer='openshift-v4' \
    subject_token_type='urn:ietf:params:oauth:token-type:access_token' \
    | jq -r '.access_token')

    if [ ! -z "$access_token" ];
    then 
    # echo "Access Token: $access_token"

    # switch back to cluster admin to get routes
    oc logout &> /dev/null
    oc login --username="$OPENSHIFT_ADMIN_USER" --password="$OPENSHIFT_ADMIN_USER_PASSWORD" "$OPENSHIFT_API_URL" &> /dev/null
    
    echo "Creating Eclipse Che workspace for user $che_user"
 
    local wksp_url=$(chectl workspace:start \
      --devfile="${WORKSHOP_DEVFILE_URL}" \
      --access-token="$access_token" &> /dev/null)
    # http --body $wksp_url 
    # echo "$che_user:$wksp_url" >> $_CURR_DIR/workspaces.txt
    fi 
  done
}

createWorkspaces::usage(){
   cat <<EOT
  -f --from <user count from>    The starting user count e.g. 1
  -t --to <user count to>        The ending user count e.g. 10
  -p --prefix <userprefix>       The username prefix e.g. user
EOT
}

createWorkspaces::description(){
  echo "Creates Che workspace for each workshop user"
}
