#!/bin/bash
createWorkspaces::run(){

  local cheKeyCloakUrl="http://$(oc get routes -n che keycloak -o yaml | yq r - 'spec.host')"
  local tokenEndpoint="$cheKeyCloakUrl/auth/realms/che/protocol/openid-connect/token"

  # Check if pre-req commands exists
  hash chectl
  hash jq
  hash http

  NL=$'\n'

  local user_from=$(readopt -f --from)
  if [ -z $user_from ]; then 
     user_from=$USERS_FROM
  fi

  local user_to=$(readopt -t --to)
  if [ -z $user_to ]; then 
     user_to=$USERS_TO
  fi
  
  local user_prefix=$(readopt -p --prefix)
   if [ -z $user_prefix ]; then 
     user_prefix=$USER_PREFIX
  fi
  
  for ((i=$user_from; i<=user_to ; i++ ));
  do
    local che_user="$user_prefix$i"
    local che_user_password="${WORKSHOP_USER_DEFAULT_PASSWORD}" 
    local token=$(http --form POST $tokenEndpoint \
    grant_type="password" client_id="che-public" \
    username="$che_user" password="$che_user_password" | jq -r '.access_token')
    # echo "$token"
    echo "Creating Eclipse Che workspace for user $user_prefix$i"
    local wsp_url=$(chectl workspace:start \
      --devfile="${WORKSHOP_DEVFILE_URL}" \
      --access-token="$token" 2>&1 | egrep -o 'https?://[^ ")]+' | tail -1 )    
    echo "$user_prefix$i:$wsp_url" >> $_CURR_DIR/workspaces.txt
  done
}

createWorkspaces::usage(){
   cat <<EOT
  -f --from <user count from>    The starting user count e.g. 1
  -t --to <user count to>        The ending user count e.g. 10
  -p --prefix <userprefix>       The username prefix e.g. user
EOT
}

createWorkspaces::description(){
  echo "Creates Che workspace for each workshop user"
}
