#!/bin/bash

createCheCluster::run() {
 chectl server:start --multiuser --platform=openshift --tls --os-oauth
}

createCheCluster::usage(){
  echo "No parameters"
}

createCheCluster::description(){
  echo "Create Eclipse Che and its components via CRD"
}