#!/bin/bash

createServicemesh::run() {
 ! oc adm new-project istio-system
 sleep 60
 oc apply -n 'istio-system' -f "$(configdir)/servicemesh/control-plane.yaml" 
}

createServicemesh::usage(){
  echo "No parameters"
}

createServicemesh::description(){
  echo "Create Eclipse Che and its components via CRD"
}