#!/bin/bash

installChe::run() {
 chectl server:start --multiuser --platform=openshift --tls --os-oauth
}

installChe::usage(){
  echo "No parameters"
}

installChe::clean(){
  echo "WIP"
}

installChe::description(){
  echo "Install Eclipse Che via Operator"
}