#!/bin/bash

installKamel::run() {
 kubectl apply -f "$(configdir)/kamel/subscription.yaml" 
 csv_status 'camel-k'
 log_success "\n Apache Camel-K (kamel) successfully installed \n"
}

installKamel::usage(){
  echo "No parameters"
}

installKamel::clean(){
  csv_delete 'camel-k'
  kubectl delete -f "$(configdir)/kamel/subscription.yaml" 
  log_success "\n Apache Camel-K (kamel) successfully unsubcribed \n"
}

installKamel::description(){
  echo "Install Apache Camel-K via Operator"
}