#!/bin/bash

installKnativeServing::run() {
 ! oc adm new-project knative-serving
 oc apply -f "$(configdir)/knative-serving/subscription.yaml" 
 oc apply -f "$(configdir)/knative-serving/cr.yaml"
}

installKnativeServing::usage(){
  echo "No parameters"
}

installKnativeServing::clean() {
  echo "WIP"
}

installKnativeServing::description(){
  echo "Install Knative Serving via Knative Serving Operator"
}