#!/bin/bash

installCatalogSources::run() {
 oc apply -f "$(configdir)/redhat-operators-csc.yaml" 
 oc apply -f "$(configdir)/community-operators-csc.yaml" 
}

installCatalogSources::usage(){
  echo "No parameters"
}

installCatalogSources::description(){
  echo "Install Operators Catalog Sources"
}