#!/bin/bash

installServicemeshAll::run() {
 local cmd_dir="$(basedir)/commands"
 local config_dir="$(basedir)/config"

 local commands=("installCatalogSources" "installServicemesh" "installServicemeshControlPlane")
 
 for command in "${commands[@]}"
 do
     source "$cmd_dir/$command"
     eval "${command}::run"
 done
}

installServicemeshAll::clean() {
 local cmd_dir="$(basedir)/commands"
 local config_dir="$(basedir)/config"

 local commands=("installCatalogSources" "installServicemesh" "installServicemeshControlPlane")
 
 for command in "${commands[@]}"
 do
     source "$cmd_dir/$command"
     eval "${command}::clean"
 done
}

installServicemeshAll::usage(){
  echo "No parameters"
}

installServicemeshAll::description(){
  echo "Install all  Servicemesh Components"
}