#!/bin/bash

installKnativeCamel::run() {
 kubectl apply -f "$(configdir)/knative-camel/subscription.yaml" 
 csv_status 'knative-camel'
 log_success "\n Knative Eventing Camel successfully installed \n"
}

installKnativeCamel::usage(){
  echo "No parameters"
}

installKnativeCamel::clean(){
 csv_delete 'knative-camel'
 kubectl delete -f "$(configdir)/knative-camel/subscription.yaml" 
 log_success "\n  Knative Eventing Camel unsubcribed \n" 
}

installKnativeCamel::description(){
  echo "Install Knative CamelSource via Operator"
}