#!/bin/bash

installChe::run() {
 ! oc adm new-project che &&\
 oc apply -f "$(configdir)/che/che-csc-subscription.yaml" 
}

installChe::usage(){
  echo "No parameters"
}

installChe::clean(){
  echo "WIP"
}

installChe::description(){
  echo "Install Eclipse Che via Operator"
}