#!/bin/bash

installPipelines::run() {
 kubectl apply -f "$(configdir)/pipelines/subscription.yaml" 
 csv_status 'openshift-pipelines'
 log_success "\n OpenShift Pipelines successfully installed \n"
}

installPipelines::usage(){
  echo "No parameters"
}

installPipelines::clean(){
  csv_delete 'openshift-pipelines'
  kubectl delete -f "$(configdir)/pipelines/subscription.yaml" 
  log_success "\n OpenShift Pipelines successfully unsubscribed \n"
}

installPipelines::description(){
  echo "Install OpenShift Pipelines via OpenShift Pipelines Operator"
}